# Generated by Django 4.0.2 on 2022-07-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profesor',
        ),
    ]
