# Generated by Django 4.0.5 on 2022-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0007_delete_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='detalle',
            field=models.TextField(default='ingresa detalle de producto', max_length=1000),
        ),
    ]
