# Generated by Django 4.0.2 on 2022-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
