# Generated by Django 3.2.6 on 2022-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
