# Generated by Django 3.2.6 on 2022-08-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_shippingaddress_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
